server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://prod-rds.cizgbl62pkt2.eu-west-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${{ secrets.POSTGRES_USER }}
    password: ${{ secrets.POSTGRES_PASSWORD }}

