name: Docker-Image-CI-CD-to-AWS-ECR
env:
  AWS_REGION  : "eu-west-1"
  APP_VERSION :  "v0.0.1"
  WORKING_DIRECTORY: ./it-specialty

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: ["it-specialty/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up
      # docker build ./it-specialty --tag diploma:${{ env.APP_VERSION }}

  cd-part:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: ${{ WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag diploma:${{ env.APP_VERSION }}
    
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region            : ${{ env.AWS_REGION }}
      
    - name: Authentication Docker Client to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS \
        --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        
    - name: Push to AWS ECR
      run: |
        docker tag diploma:${{ env.APP_VERSION }} \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/diploma:${{ env.APP_VERSION }}
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/diploma:${{ env.APP_VERSION }}
