# This is a basic workflow to help you get started with Actions

name: My-Github-Actions-Learning
env:
  APP_NAME    : "MyAppName"
  PACKAGE_NAME: "My_App_Deploy_File-${{ github.sha }}"
  
on:
  push:
    branches: [ master ]

jobs:
  Learning-tests:
    runs-on: ubuntu-latest
    needs: [Testing-commands]
    env:
      VAR_1: "Job Level 1 Varible"
      VAR_2: "Job Level 2 Varible"
    
    steps:
      - name: Run first job's command
        run: echo "Hello, world from learning-test!"
      
      - name: Printing variables
        run: |
          echo "My application is ${{ env.APP_NAME }}"
          echo "My deploying package name ${{ env.PACKAGE_NAME }}"
          
      - name: Print environment variables
        run: |
          echo "Var 1 = ${{ env.VAR_1 }}"
          echo "Var 2 = ${{ env.VAR_2 }}"
          echo "Var 3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "Super local env VAR"
      
  Testing-commands:
    runs-on: ubuntu-latest
    steps:
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Hello, world from testing-commands!"
          echo "Second parallel command."
      
      - name: Listing runner's directory before a/c@v2
        run: ls -la
        
      - name: Git clone my repo
        uses: actions/checkout@v2
        
      - name: Listing runner's directory after a/c@v2
        run: ls -la
        
      - name: Let's test some packages if they are here 1
        run: aws --version
        
      - name: Let's test some packages if they are here 2
        run: which zip
        
      - name: Let's test some packages if they are here 3
        run: docker --version
