---
name: General_Linter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          # Main settings
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: (\.github.*|.*inventory.ya?ml|.*docker-compose.ya?ml)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tools
          ANSIBLE_DIRECTORY: .
          VALIDATE_ANSIBLE: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_ENV: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_TERRAGRUNT: true
          VALIDATE_YAML: true